steps:
  # Step 1: Build the Docker image (referencing Dockerfile)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/devoconnector', '.']

  # Step 2: Push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/devoconnector']

  # Step 3: Deploy the Docker image to Google Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
        'run',
        'deploy',
        'devoconnector',
        '--image=gcr.io/$PROJECT_ID/devoconnector',
        '--platform=managed',
        '--region=us-central1',
        '--allow-unauthenticated'
       # Allow unauthenticated access (remove if not needed)
      ]
  options:
    logging: CLOUD_LOGGING_ONLY